// Package models contains the types for schema 'agency_portal'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
)

// Booking represents a row from 'agency_portal.BOOKING'.
type Booking struct {
	UUID       []byte     `json:"UUID"`       // UUID
	Namespace  Namespace  `json:"NAMESPACE"`  // NAMESPACE
	Collection Collection `json:"COLLECTION"` // COLLECTION
	Metadata   JSON       `json:"METADATA"`   // METADATA

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Booking exists in the database.
func (b *Booking) Exists() bool {
	return b._exists
}

// Deleted provides information if the Booking has been deleted from the database.
func (b *Booking) Deleted() bool {
	return b._deleted
}

// Insert inserts the Booking to the database.
func (b *Booking) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if b._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO agency_portal.BOOKING (` +
		`UUID, NAMESPACE, COLLECTION, METADATA` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, b.UUID, b.Namespace, b.Collection, b.Metadata)
	_, err = db.Exec(sqlstr, b.UUID, b.Namespace, b.Collection, b.Metadata)
	if err != nil {
		return err
	}

	// set existence
	b._exists = true

	return nil
}

// Update updates the Booking in the database.
func (b *Booking) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !b._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if b._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE agency_portal.BOOKING SET ` +
		`NAMESPACE = ?, COLLECTION = ?, METADATA = ?` +
		` WHERE UUID = ?`

	// run query
	XOLog(sqlstr, b.Namespace, b.Collection, b.Metadata, b.UUID)
	_, err = db.Exec(sqlstr, b.Namespace, b.Collection, b.Metadata, b.UUID)
	return err
}

// Save saves the Booking to the database.
func (b *Booking) Save(db XODB) error {
	if b.Exists() {
		return b.Update(db)
	}

	return b.Insert(db)
}

// Delete deletes the Booking from the database.
func (b *Booking) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !b._exists {
		return nil
	}

	// if deleted, bail
	if b._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM agency_portal.BOOKING WHERE UUID = ?`

	// run query
	XOLog(sqlstr, b.UUID)
	_, err = db.Exec(sqlstr, b.UUID)
	if err != nil {
		return err
	}

	// set deleted
	b._deleted = true

	return nil
}

// BookingByUUID retrieves a row from 'agency_portal.BOOKING' as a Booking.
//
// Generated from index 'BOOKING_UUID_pkey'.
func BookingByUUID(db XODB, uuid []byte) (*Booking, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`UUID, NAMESPACE, COLLECTION, METADATA ` +
		`FROM agency_portal.BOOKING ` +
		`WHERE UUID = ?`

	// run query
	XOLog(sqlstr, uuid)
	b := Booking{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, uuid).Scan(&b.UUID, &b.Namespace, &b.Collection, &b.Metadata)
	if err != nil {
		return nil, err
	}

	return &b, nil
}
