// Package models contains the types for schema 'agency_portal'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"errors"
)

// Collection is the 'COLLECTION' enum type from schema 'agency_portal'.
type Collection uint16

const (
	// CollectionBackupCareBooking is the 'BACKUP_CARE_BOOKING' Collection.
	CollectionBackupCareBooking = Collection(1)
)

// String returns the string value of the Collection.
func (c Collection) String() string {
	var enumVal string

	switch c {
	case CollectionBackupCareBooking:
		enumVal = "BACKUP_CARE_BOOKING"
	}

	return enumVal
}

// MarshalText marshals Collection into text.
func (c Collection) MarshalText() ([]byte, error) {
	return []byte(c.String()), nil
}

// UnmarshalText unmarshals Collection from text.
func (c *Collection) UnmarshalText(text []byte) error {
	switch string(text) {
	case "BACKUP_CARE_BOOKING":
		*c = CollectionBackupCareBooking

	default:
		return errors.New("invalid Collection")
	}

	return nil
}

// Value satisfies the sql/driver.Valuer interface for Collection.
func (c Collection) Value() (driver.Value, error) {
	return c.String(), nil
}

// Scan satisfies the database/sql.Scanner interface for Collection.
func (c *Collection) Scan(src interface{}) error {
	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid Collection")
	}

	return c.UnmarshalText(buf)
}
