// Package models contains the types for schema 'agency_portal'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"errors"
)

// Namespace is the 'NAMESPACE' enum type from schema 'agency_portal'.
type Namespace uint16

const (
	// NamespaceCzen is the 'CZEN' Namespace.
	NamespaceCzen = Namespace(1)
)

// String returns the string value of the Namespace.
func (n Namespace) String() string {
	var enumVal string

	switch n {
	case NamespaceCzen:
		enumVal = "CZEN"
	}

	return enumVal
}

// MarshalText marshals Namespace into text.
func (n Namespace) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText unmarshals Namespace from text.
func (n *Namespace) UnmarshalText(text []byte) error {
	switch string(text) {
	case "CZEN":
		*n = NamespaceCzen

	default:
		return errors.New("invalid Namespace")
	}

	return nil
}

// Value satisfies the sql/driver.Valuer interface for Namespace.
func (n Namespace) Value() (driver.Value, error) {
	return n.String(), nil
}

// Scan satisfies the database/sql.Scanner interface for Namespace.
func (n *Namespace) Scan(src interface{}) error {
	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid Namespace")
	}

	return n.UnmarshalText(buf)
}
