// Package models contains the types for schema 'agency_portal'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"errors"
)

// Source is the 'SOURCE' enum type from schema 'agency_portal'.
type Source uint16

const (
	// SourceTriage is the 'TRIAGE' Source.
	SourceTriage = Source(1)

	// SourceCsr is the 'CSR' Source.
	SourceCsr = Source(2)
)

// String returns the string value of the Source.
func (s Source) String() string {
	var enumVal string

	switch s {
	case SourceTriage:
		enumVal = "TRIAGE"

	case SourceCsr:
		enumVal = "CSR"
	}

	return enumVal
}

// MarshalText marshals Source into text.
func (s Source) MarshalText() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalText unmarshals Source from text.
func (s *Source) UnmarshalText(text []byte) error {
	switch string(text) {
	case "TRIAGE":
		*s = SourceTriage

	case "CSR":
		*s = SourceCsr

	default:
		return errors.New("invalid Source")
	}

	return nil
}

// Value satisfies the sql/driver.Valuer interface for Source.
func (s Source) Value() (driver.Value, error) {
	return s.String(), nil
}

// Scan satisfies the database/sql.Scanner interface for Source.
func (s *Source) Scan(src interface{}) error {
	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid Source")
	}

	return s.UnmarshalText(buf)
}
