// Package models contains the types for schema 'agency_portal'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"errors"
)

// Statu is the 'STATUS' enum type from schema 'agency_portal'.
type Statu uint16

const (
	// StatuPending is the 'PENDING' Statu.
	StatuPending = Statu(1)

	// StatuFulfilled is the 'FULFILLED' Statu.
	StatuFulfilled = Statu(2)

	// StatuCancelled is the 'CANCELLED' Statu.
	StatuCancelled = Statu(3)
)

// String returns the string value of the Statu.
func (s Statu) String() string {
	var enumVal string

	switch s {
	case StatuPending:
		enumVal = "PENDING"

	case StatuFulfilled:
		enumVal = "FULFILLED"

	case StatuCancelled:
		enumVal = "CANCELLED"
	}

	return enumVal
}

// MarshalText marshals Statu into text.
func (s Statu) MarshalText() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalText unmarshals Statu from text.
func (s *Statu) UnmarshalText(text []byte) error {
	switch string(text) {
	case "PENDING":
		*s = StatuPending

	case "FULFILLED":
		*s = StatuFulfilled

	case "CANCELLED":
		*s = StatuCancelled

	default:
		return errors.New("invalid Statu")
	}

	return nil
}

// Value satisfies the sql/driver.Valuer interface for Statu.
func (s Statu) Value() (driver.Value, error) {
	return s.String(), nil
}

// Scan satisfies the database/sql.Scanner interface for Statu.
func (s *Statu) Scan(src interface{}) error {
	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid Statu")
	}

	return s.UnmarshalText(buf)
}
